// User prompt command serialization, extracted as a pure inline function so it
// can be unit-tested without spawning a node subprocess. The GUI sends user
// prompts to the RPC as a `prompt` command (the only recognized RpcCommand
// that carries a free text message). Wire schema:
//   {"type":"prompt","id":<unique id>,"message":<msg>,"streamingBehavior":"steer"}
// The runtime parses the command with Node's strict JSON.parse, so the message
// value must be a valid JSON string literal. Escaping only `"` and `\` is not
// enough: a literal newline (or other control byte) inside the string would
// make the whole line invalid JSON and the prompt is rejected. Every control
// character (U+0000..U+001F) is therefore escaped, with short escapes for the
// common ones (`\b \t \n \f \r`).
//
// Each prompt carries a unique per-send id (generated by nextPromptId)
// for request/response correlation, and `streamingBehavior:"steer"` so the
// runtime queues it as a steering message while the belief-loop is running
// instead of rejecting it as a concurrent user-prompt. When idle, the runtime
// ignores streamingBehavior and starts a normal user-prompt; when running it
// queues the message via steer. This matches the documented rpc.md contract.
//
// The four domain-state commands below (bootstrap and the Frame pane's two
// acts) live here so that every command the GUI sends is serialized by one
// unit-testable file. They are deliberately separate functions from
// serializePromptCommand: `approve_frame` is the only command that means
// consent, and the way that stays true is that it is not reachable by typing.

#pragma once

#include <atomic>
#include <cstdio>
#include <string>

namespace pie::gui {

// Unique per-send user prompt id for RPC request/response correlation. The
// runtime's own client uses a `req_`-prefixed monotonic counter (see
// rpc-client.ts); mirror that convention here so ids are unique per send and
// need no platform crypto/uuid facility.
inline std::string nextPromptId() {
    static std::atomic<long> counter{0};
    return "req_" + std::to_string(counter.fetch_add(1, std::memory_order_relaxed));
}

// One JSON string literal body (no surrounding quotes). Shared by every
// serializer below so a new command cannot accidentally ship a weaker escaper.
inline std::string escapeJsonString(const std::string& text) {
    std::string escaped;
    escaped.reserve(text.size() + 16);
    for (char c : text) {
        switch (c) {
            case '"':  escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b"; break;
            case '\t': escaped += "\\t"; break;
            case '\n': escaped += "\\n"; break;
            case '\f': escaped += "\\f"; break;
            case '\r': escaped += "\\r"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20u) {
                    char buf[8];
                    std::snprintf(buf, sizeof(buf), "\\u%04x", static_cast<unsigned int>(static_cast<unsigned char>(c)));
                    escaped += buf;
                } else {
                    escaped += c;
                }
        }
    }
    return escaped;
}

inline std::string serializePromptCommand(const std::string& id, const std::string& message) {
    return "{\"type\":\"prompt\",\"id\":\"" + escapeJsonString(id) +
           "\",\"message\":\"" + escapeJsonString(message) + "\",\"streamingBehavior\":\"steer\"}";
}

// ---------------------------------------------------------------------------
// Domain-state commands (docs/milestones.md §3.4, §5.3)
// ---------------------------------------------------------------------------
//
// The bootstrap writes these two on connect, snapshot first. Both are
// id-carrying request/response commands; the ids are what let the bootstrap
// recognise its own answers, since a `response` line names the command it
// answers but a client may also match on the id it chose.

inline std::string serializeGetSnapshotCommand(const std::string& id) {
    return "{\"type\":\"get_domain_snapshot\",\"id\":\"" + escapeJsonString(id) + "\"}";
}

inline std::string serializeGetStateCommand(const std::string& id) {
    return "{\"type\":\"get_state\",\"id\":\"" + escapeJsonString(id) + "\"}";
}

// `approve_frame` is THE ONLY command that releases the pause on a reading
// (docs/milestones.md §3.4). A plain prompt never does — so this is deliberately
// a separate function from serializePromptCommand and never shares its call site.
//
// `versionId` is optional on the wire: an empty one is omitted rather than sent
// as "", which the runtime would read as a version literally named "". Omitting
// it asks the runtime to act on whatever version is currently awaiting a
// response, which is exactly the case the Frame pane has no version for.
inline std::string serializeApproveFrameCommand(const std::string& id, const std::string& versionId) {
    std::string cmd = "{\"type\":\"approve_frame\",\"id\":\"" + escapeJsonString(id) + "\"";
    if (!versionId.empty()) cmd += ",\"versionId\":\"" + escapeJsonString(versionId) + "\"";
    cmd += "}";
    return cmd;
}

// The user's objection to a published reading. Its own command and its own input
// box in the UI: an objection is not a prompt and must not be typed into one.
inline std::string serializeFrameCorrectCommand(const std::string& id, const std::string& message) {
    return "{\"type\":\"frame_correct\",\"id\":\"" + escapeJsonString(id) +
           "\",\"message\":\"" + escapeJsonString(message) + "\"}";
}

} // namespace pie::gui
