// User prompt command serialization, extracted as a pure inline function so it
// can be unit-tested without spawning a node subprocess. The GUI sends user
// prompts to the RPC as a `prompt` command (the only recognized RpcCommand
// that carries a free text message). Wire schema:
//   {"type":"prompt","id":<unique id>,"message":<msg>,"streamingBehavior":"steer"}
// The runtime parses the command with Node's strict JSON.parse, so the message
// value must be a valid JSON string literal. Escaping only `"` and `\` is not
// enough: a literal newline (or other control byte) inside the string would
// make the whole line invalid JSON and the prompt is rejected. Every control
// character (U+0000..U+001F) is therefore escaped, with short escapes for the
// common ones (`\b \t \n \f \r`).
//
// Each prompt carries a unique per-send id (generated by nextPromptId)
// for request/response correlation, and `streamingBehavior:"steer"` so the
// runtime queues it as a steering message while the belief-loop is running
// instead of rejecting it as a concurrent user-prompt. When idle, the runtime
// ignores streamingBehavior and starts a normal user-prompt; when running it
// queues the message via steer. This matches the documented rpc.md contract.

#pragma once

#include <atomic>
#include <cstdio>
#include <string>

namespace pie::gui {

// Unique per-send user prompt id for RPC request/response correlation. The
// runtime's own client uses a `req_`-prefixed monotonic counter (see
// rpc-client.ts); mirror that convention here so ids are unique per send and
// need no platform crypto/uuid facility.
inline std::string nextPromptId() {
    static std::atomic<long> counter{0};
    return "req_" + std::to_string(counter.fetch_add(1, std::memory_order_relaxed));
}

inline std::string serializePromptCommand(const std::string& id, const std::string& message) {
    std::string escaped;
    escaped.reserve(message.size() + 16);
    for (char c : message) {
        switch (c) {
            case '"':  escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b"; break;
            case '\t': escaped += "\\t"; break;
            case '\n': escaped += "\\n"; break;
            case '\f': escaped += "\\f"; break;
            case '\r': escaped += "\\r"; break;
            default:
                if (static_cast<unsigned char>(c) < 0x20u) {
                    char buf[8];
                    std::snprintf(buf, sizeof(buf), "\\u%04x", static_cast<unsigned int>(static_cast<unsigned char>(c)));
                    escaped += buf;
                } else {
                    escaped += c;
                }
        }
    }
    return "{\"type\":\"prompt\",\"id\":\"" + id +
           "\",\"message\":\"" + escaped + "\",\"streamingBehavior\":\"steer\"}";
}

} // namespace pie::gui
